/**
 * AI Knowledge Capture Module
 * 
 * Captures and structures knowledge generated by the system for learning purposes.
 * 
 * @module knowledge
 */

export { storeDesignKnowledge } from './storage.js';
export { DesignKnowledgeSchema } from './schema.js';