from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.gen_requirements import main, render_requirements


ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PINS = Path(__file__).resolve().parent / "fixtures" / "beat-engine" / "pins.json"
FIXTURE_REQUIREMENTS = (
    "# Generated by scripts/gen_requirements.py from pins.json; do not edit.\n"
    "git+https://github.com/JWSound/BEAT_Engine.git@"
    "0123456789abcdef0123456789abcdef01234567#egg=beat-engine\n"
    "git+https://github.com/m3gnus/hornlab-sim.git@"
    "abcdef0123456789abcdef0123456789abcdef01#egg=hornlab-sim\n"
)
VALID_SHA = "0123456789abcdef0123456789abcdef01234567"


def _write_pin(tmp_path: Path, module: str, repo: object, sha: object) -> Path:
    path = tmp_path / "pins.json"
    path.write_text(
        json.dumps({"modules": {module: {"repo": repo, "sha": sha}}}),
        encoding="utf-8",
    )
    return path


def test_fixture_renders_exact_requirement_lines_in_distribution_order(tmp_path: Path) -> None:
    assert render_requirements(FIXTURE_PINS) == FIXTURE_REQUIREMENTS

    output = tmp_path / "requirements-pins.txt"
    args = ["--pins", str(FIXTURE_PINS), "--output", str(output)]
    assert main(args) == 0
    assert output.read_bytes() == FIXTURE_REQUIREMENTS.encode("utf-8")
    assert main([*args, "--check"]) == 0


def test_current_pins_match_checked_in_requirements() -> None:
    output = ROOT / "server" / "requirements-pins.txt"
    assert render_requirements(ROOT / "pins.json").encode("utf-8") == output.read_bytes()
    assert main(["--pins", str(ROOT / "pins.json"), "--output", str(output), "--check"]) == 0


@pytest.mark.parametrize("module,repository", [("beat-engine", "JWSound/BEAT_Engine"), ("hornlab-sim", "m3gnus/hornlab-sim")])
@pytest.mark.parametrize(
    "repo_template",
    [
        "https://github.com/other/{name}.git",
        "https://example.com/{repository}.git",
        "http://github.com/{repository}.git",
        "git@github.com:{repository}.git",
        "https://github.com/{repository}",
        "https://github.com/{repository}.git/",
        "https://github.com/{repository}.git?ref=main",
        None,
    ],
)
def test_repository_validation_stays_exact(
    tmp_path: Path, module: str, repository: str, repo_template: str | None
) -> None:
    repo = (
        repo_template.format(repository=repository, name=repository.split("/")[1])
        if repo_template
        else None
    )
    pins = _write_pin(tmp_path, module, repo, VALID_SHA)
    with pytest.raises(ValueError, match="expected"):
        render_requirements(pins)


@pytest.mark.parametrize(
    "module,repo",
    [
        ("beat-engine", "https://github.com/m3gnus/BEAT_Engine.git"),
        ("beat-engine", "https://github.com/JWSound/beat-engine.git"),
        ("beat-engine", "https://github.com/m3gnus/beat-engine.git"),
        ("beat-engine", "https://github.com/m3gnus/beat_engine.git"),
        ("hornlab-sim", "https://github.com/JWSound/BEAT_Engine.git"),
        ("hornlab-sim", "https://github.com/JWSound/hornlab-sim.git"),
        ("other-engine", "https://github.com/JWSound/BEAT_Engine.git"),
    ],
)
def test_repository_mapping_is_only_for_the_explicit_distribution(
    tmp_path: Path, module: str, repo: str
) -> None:
    pins = _write_pin(tmp_path, module, repo, VALID_SHA)
    with pytest.raises(ValueError, match="expected"):
        render_requirements(pins)


@pytest.mark.parametrize("module,repository", [("beat-engine", "JWSound/BEAT_Engine"), ("hornlab-sim", "m3gnus/hornlab-sim")])
@pytest.mark.parametrize(
    "sha",
    ["main", VALID_SHA[:7], VALID_SHA[:-1], VALID_SHA + "0", VALID_SHA.upper(), "g" * 40, VALID_SHA + "\n", None, 123],
)
def test_sha_validation_stays_exact(
    tmp_path: Path, module: str, repository: str, sha: object
) -> None:
    pins = _write_pin(tmp_path, module, f"https://github.com/{repository}.git", sha)
    with pytest.raises(ValueError, match="lowercase 40-character git SHA"):
        render_requirements(pins)


def test_invalid_mapped_pin_reports_failure_without_writing(tmp_path: Path, capsys) -> None:
    pins = _write_pin(tmp_path, "beat-engine", "https://github.com/JWSound/BEAT_Engine.git", "main")
    output = tmp_path / "requirements-pins.txt"
    output.write_text("existing\n", encoding="utf-8")
    assert main(["--pins", str(pins), "--output", str(output)]) == 2
    assert "lowercase 40-character git SHA" in capsys.readouterr().err
    assert output.read_text(encoding="utf-8") == "existing\n"
