#!/usr/bin/env python3
"""Generate deterministic git requirements from the Waveguide v2 pin manifest."""

from __future__ import annotations

import argparse
import difflib
import json
import os
from pathlib import Path
import re
import sys
from typing import Any


_IMPORT_ROOT = Path(
    os.environ.get("WG2_APP_ROOT") or Path(__file__).resolve().parents[1]
).expanduser().resolve()
if str(_IMPORT_ROOT) not in sys.path:
    sys.path.insert(0, str(_IMPORT_ROOT))

from server.platform.paths import app_root  # noqa: E402


REPO_ROOT = app_root()
DEFAULT_PINS = REPO_ROOT / "pins.json"
DEFAULT_OUTPUT = REPO_ROOT / "server" / "requirements-pins.txt"
SHA_RE = re.compile(r"[0-9a-f]{40}\Z")


def render_requirements(pins_path: Path = DEFAULT_PINS) -> str:
    """Render validated pins in module-name order."""

    payload: Any = json.loads(pins_path.read_text(encoding="utf-8"))
    modules = payload.get("modules") if isinstance(payload, dict) else None
    if not isinstance(modules, dict):
        raise ValueError(f"{pins_path} must contain an object named 'modules'")

    lines = ["# Generated by scripts/gen_requirements.py from pins.json; do not edit."]
    for module in sorted(modules):
        pin = modules[module]
        if not isinstance(module, str) or not isinstance(pin, dict):
            raise ValueError(f"Invalid module entry {module!r} in {pins_path}")
        repo = pin.get("repo")
        sha = pin.get("sha")
        expected_repo = f"https://github.com/m3gnus/{module}.git"
        if repo != expected_repo:
            raise ValueError(
                f"Pin {module!r} has repo {repo!r}; expected {expected_repo!r}"
            )
        if not isinstance(sha, str) or SHA_RE.fullmatch(sha) is None:
            raise ValueError(f"Pin {module!r} must have a lowercase 40-character git SHA")
        lines.append(f"git+{repo}@{sha}#egg={module}")
    return "\n".join(lines) + "\n"


def check_output(expected: str, output_path: Path) -> bool:
    try:
        actual = output_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        actual = ""
    if actual == expected:
        return True
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(output_path),
        tofile=f"generated from {DEFAULT_PINS}",
    )
    sys.stderr.writelines(diff)
    return False


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff stale output; do not write")
    parser.add_argument("--pins", type=Path, default=DEFAULT_PINS, help=argparse.SUPPRESS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help=argparse.SUPPRESS)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        rendered = render_requirements(args.pins)
        if args.check:
            return 0 if check_output(rendered, args.output) else 1
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8", newline="\n")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(
            f"Could not generate pinned requirements: {exc}. Fix pins.json or the output "
            "path, then run this command again.",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
