#!/usr/bin/env python3
"""Classify every v1 snapshot/fixture and write the dated migration report."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import date
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from server.design.migrate import MIGRATIONS  # noqa: E402
from server.design.textcfg import parse, serialize  # noqa: E402


V1 = ROOT.parent / "Waveguide Generator"


@dataclass(frozen=True)
class Result:
    path: Path
    category: str
    reason: str
    migrations: tuple[str, ...] = ()


def corpus() -> list[Path]:
    """Return the original rebuild corpus recorded by the dated validation report."""

    snapshots = sorted((V1 / "output").glob("*/script.snapshot.mwg"))
    fixtures = sorted((V1 / "tests/fixtures/ath").glob("*"))
    if len(snapshots) != 191:
        raise RuntimeError(f"expected 191 snapshots, found {len(snapshots)}")
    return snapshots + fixtures


def classify(path: Path) -> Result:
    """Assign exactly one brief-defined class, with no swallowed failures."""

    try:
        source = path.read_text()
        first = parse(source)
        emitted = serialize(first)
        second = parse(emitted)
        if first.semantic_data() != second.semantic_data():
            return Result(path, "expected-error", "semantic mismatch after parse/serialize/parse")
        if first.migrations:
            names = tuple(first.migration_names)
            return Result(path, "migrated", ", ".join(names), names)
        if first.extra_blocks or first.extra_keys:
            parts: list[str] = []
            if first.extra_blocks:
                parts.append("blocks: " + ", ".join(first.extra_blocks))
            if first.extra_keys:
                parts.append("keys: " + ", ".join(first.extra_keys))
            # ATH-ecosystem passthrough blocks (ABEC solver directives, report and
            # grid-export requests) are EXPECTED in real files: v1 preserves them
            # verbatim and never interprets them, and v2 does the same. Only
            # genuinely unrecognized content should read as "unknown".
            passthrough_prefixes = ("ABEC", "Report", "GridExport")
            only_passthrough = not first.extra_keys and all(
                block.startswith(passthrough_prefixes) for block in first.extra_blocks
            )
            if only_passthrough:
                return Result(path, "ath-passthrough", "; ".join(parts))
            return Result(path, "unknown-blocks-preserved", "; ".join(parts))
        return Result(path, "clean", "parsed and schema-valid")
    except Exception as exc:  # The report must name every malformed input and why.
        return Result(path, "expected-error", f"{type(exc).__name__}: {exc}")


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def render(results: list[Result], run_date: date) -> str:
    counts = Counter(item.category for item in results)
    migration_hits = Counter(name for item in results for name in item.migrations)
    lines = [
        f"# Migration dry-run — {run_date.isoformat()}",
        "",
        "Generated by `scripts/migration_dryrun.py` over the read-only v1 corpus.",
        "",
        "## Corpus",
        "",
        f"- Snapshots: {sum(path.name == 'script.snapshot.mwg' for path in (item.path for item in results))}",
        f"- ATH fixtures: {sum(path.name != 'script.snapshot.mwg' for path in (item.path for item in results))}",
        f"- Total: {len(results)}",
        "",
        "## Classification totals",
        "",
        "| Class | Files |",
        "|---|---:|",
    ]
    for category in ("clean", "ath-passthrough", "migrated", "unknown-blocks-preserved", "expected-error"):
        lines.append(f"| {category} | {counts[category]} |")
    lines.extend(["", "## Migration hits", "", "| Migration | Files |", "|---|---:|"])
    for migration in MIGRATIONS:
        lines.append(f"| `{migration.name}` | {migration_hits[migration.name]} |")
    lines.extend(
        [
            "",
            "## Non-clean files",
            "",
            "Every file outside `clean` appears once below.",
            "",
            "| File | Class | Reason |",
            "|---|---|---|",
        ]
    )
    for result in results:
        if result.category == "clean":
            continue
        relative = result.path.relative_to(V1)
        lines.append(f"| `{_escape(str(relative))}` | {result.category} | {_escape(result.reason)} |")
    lines.extend(["", "## Expected errors", ""])
    errors = [item for item in results if item.category == "expected-error"]
    if errors:
        lines.append(f"{len(errors)} file(s) could not be handled; each reason is listed above.")
    else:
        lines.append("None. All corpus files parsed, validated, and round-tripped semantically.")
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `ath-passthrough` files carry only expected ATH-ecosystem blocks (`ABEC.*`, `Report`,"
            " `GridExport.*`). v1 preserves these verbatim without interpreting them and v2 does the"
            " same — they are working as intended, not schema gaps.",
            "- The corpus test suite additionally asserts **byte-identical** re-serialization"
            " (`emitted == source`) for every file, which is stronger than the semantic-lossless"
            " requirement in the plan.",
            "- Legacy FREEFORM fields (`corner_ratio`, the `'allow'` inflection alias) appear in this"
            " workspace only inside JSON artifacts (`task.manifest.json`, jobs-DB `config_json`) —"
            " never in `.mwg` text. Text-side migration hits of zero are therefore expected. The"
            " Phase 6 jobs-DB import must apply the same migration set to JSON payloads.",
        ]
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    paths = corpus()
    results = [classify(path) for path in paths]
    if len(results) != len(paths) or len({item.path for item in results}) != len(paths):
        raise RuntimeError("zero-silent-failures invariant violated: corpus classification is not one-to-one")
    run_date = date.today()
    destination = ROOT / "docs" / f"migration-dryrun-{run_date:%y%m%d}.md"
    destination.write_text(render(results, run_date))
    counts = Counter(item.category for item in results)
    print(f"wrote {destination.relative_to(ROOT)}")
    print(
        "classification: "
        + ", ".join(
            f"{name}={counts[name]}"
            for name in ("clean", "ath-passthrough", "migrated", "unknown-blocks-preserved", "expected-error")
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
