"""Generate the native Onshape waveguide feature without making API calls."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any


FEATURE_TYPE = "wgWaveguide"
STD_VERSION = "3044"

_PARAMETER_FIELDS = (
    "throat_dia",
    "mouth_w",
    "mouth_h",
    "depth",
    "wall_t",
    "vertical_offset",
    "enc_w",
    "enc_h",
    "enc_depth",
    "enc_edge",
    "enc_x0",
    "enc_y0",
    "enc_z_front",
)


def ring_stations(n_stations: int, wanted: int) -> list[int]:
    """Choose loft sections, denser where the throat turns most sharply."""

    if n_stations <= 0:
        return []
    if n_stations == 1:
        return [0]
    if wanted <= 1:
        return [0, n_stations - 1]
    if wanted >= n_stations:
        return list(range(n_stations))
    raw = [
        int(round((n_stations - 1) * (index / (wanted - 1)) ** 1.6))
        for index in range(wanted)
    ]
    return sorted(set(raw) | {0, n_stations - 1})


def _parameters_from(manifest: Mapping[str, Any]) -> dict[str, float]:
    values: dict[str, float] = {}
    entries = manifest.get("parameters") or []
    if not isinstance(entries, Sequence) or isinstance(entries, (str, bytes)):
        return values
    for entry in entries:
        if not isinstance(entry, Mapping):
            continue
        name = str(entry.get("name") or "")
        raw = entry.get("value")
        if isinstance(raw, bool) or not isinstance(raw, (int, float)):
            continue
        for field in _PARAMETER_FIELDS:
            if name.endswith("_" + field):
                values[field] = float(raw)
    return values


def _number(value: object, *, label: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{label} must be numeric")
    return float(value)


def build_featurescript(
    grid: Mapping[str, Any],
    manifest: Mapping[str, Any],
    *,
    sections: int = 40,
) -> str:
    """Return the complete Feature Studio source for a realised point grid."""

    inner = grid.get("inner_points")
    ring_z = grid.get("ring_z_mm")
    if not isinstance(inner, Sequence) or not inner:
        raise ValueError("point-grid.json has no inner_points")
    if not isinstance(ring_z, Sequence) or isinstance(ring_z, (str, bytes)):
        raise ValueError("point-grid.json has no ring_z_mm")
    first_ring = inner[0]
    if not isinstance(first_ring, Sequence) or not first_ring:
        raise ValueError("point-grid.json has no inner ring stations")
    n_stations = len(first_ring)
    if len(ring_z) != n_stations:
        raise ValueError("point-grid.json ring_z_mm does not match inner_points")

    rings: list[str] = []
    for station in ring_stations(n_stations, sections):
        xy: list[tuple[float, float]] = []
        for radial_index, radial_points in enumerate(inner):
            if not isinstance(radial_points, Sequence) or len(radial_points) != n_stations:
                raise ValueError("point-grid.json inner_points rings are inconsistent")
            point = radial_points[station]
            if not isinstance(point, Sequence) or len(point) < 2:
                raise ValueError(
                    f"point-grid.json inner point {radial_index}:{station} is invalid"
                )
            xy.append(
                (
                    _number(point[0], label="inner point x"),
                    _number(point[1], label="inner point y"),
                )
            )
        # skFitSpline closes into a region only when the first point repeats;
        # isPeriodic alone leaves an open sketch that the loft cannot use.
        xy.append(xy[0])
        points = ",\n            ".join(
            f"vector({x:.6f}, {y:.6f}) * millimeter" for x, y in xy
        )
        rings.append(
            "    {\n"
            f'        "z" : {_number(ring_z[station], label="ring z"):.6f} * millimeter,\n'
            f'        "points" : [\n            {points}\n        ]\n'
            "    }"
        )

    parameters = _parameters_from(manifest)
    enclosure = manifest.get("enclosure")
    edge_value = enclosure.get("edge_type", 1) if isinstance(enclosure, Mapping) else 1
    edge_type = int(edge_value) if isinstance(edge_value, (int, float)) else 1

    return f'''FeatureScript {STD_VERSION};
import(path : "onshape/std/geometry.fs", version : "{STD_VERSION}.0");

// Generated by Waveguide Generator from the realized point grid. Editing these
// numbers does not change the WG design; send again from WG instead.
const WG_RINGS = [
{",\n".join(rings)}
];

const WG_ENCLOSURE = {{
    "width"    : {parameters.get("enc_w", 0.0):.6f} * millimeter,
    "height"   : {parameters.get("enc_h", 0.0):.6f} * millimeter,
    "depth"    : {parameters.get("enc_depth", 0.0):.6f} * millimeter,
    "edge"     : {parameters.get("enc_edge", 0.0):.6f} * millimeter,
    "x0"       : {parameters.get("enc_x0", 0.0):.6f} * millimeter,
    "y0"       : {parameters.get("enc_y0", 0.0):.6f} * millimeter,
    "zFront"   : {parameters.get("enc_z_front", 0.0):.6f} * millimeter,
    "edgeType" : {edge_type}
}};

annotation {{ "Feature Type Name" : "WG Waveguide" }}
export const {FEATURE_TYPE} = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {{
        annotation {{ "Name" : "Build enclosure" }}
        definition.buildEnclosure is boolean;
    }}
    {{
        // ---- the bore: one sketch per ring, lofted ----
        var profiles = [];
        for (var i = 0; i < size(WG_RINGS); i += 1)
        {{
            var ring = WG_RINGS[i];
            var sketchId = id + ("wgRing" ~ i);
            var sk = newSketchOnPlane(context, sketchId, {{
                    "sketchPlane" : plane(vector(0 * millimeter, 0 * millimeter, ring.z),
                                          vector(0, 0, 1))
            }});
            // skFitSpline is the real FeatureScript function; similarly named
            // interpolation helpers silently create no sketch geometry.
            skFitSpline(sk, "profile", {{ "points" : ring.points, "isPeriodic" : true }});
            skSolve(sk);
            profiles = append(profiles, qSketchRegion(sketchId, false));
        }}

        opLoft(context, id + "wgLoft", {{
                "profileSubqueries" : profiles,
                "bodyType" : ToolBodyType.SOLID
        }});
        setProperty(context, {{
                "entities" : qCreatedBy(id + "wgLoft", EntityType.BODY),
                "propertyType" : PropertyType.NAME,
                "value" : "WG bore (cut tool)"
        }});

        if (!definition.buildEnclosure)
        {{
            return;
        }}

        // ---- the enclosure box, from the managed WG dimensions ----
        var enclosureSketchId = id + "wgEnclosureSketch";
        var enclosureSketch = newSketchOnPlane(context, enclosureSketchId, {{
                "sketchPlane" : plane(vector(0 * millimeter, 0 * millimeter, WG_ENCLOSURE.zFront),
                                      vector(0, 0, 1))
        }});
        skRectangle(enclosureSketch, "outline", {{
                "firstCorner" : vector(WG_ENCLOSURE.x0, WG_ENCLOSURE.y0),
                "secondCorner" : vector(WG_ENCLOSURE.x0 + WG_ENCLOSURE.width,
                                        WG_ENCLOSURE.y0 + WG_ENCLOSURE.height)
        }});
        skSolve(enclosureSketch);

        opExtrude(context, id + "wgEnclosure", {{
                "entities" : qSketchRegion(enclosureSketchId, false),
                "direction" : vector(0, 0, -1),
                "endBound" : BoundingType.BLIND,
                "endDepth" : WG_ENCLOSURE.depth
        }});

        // ---- edge treatment on EVERY box edge ----
        // The mesher rounds the plan corners with corner_radius = clamped_edge
        // AND insets both rims by the same value, so all twelve edges carry it.
        // Treating only the vertical corners left the front and back rims sharp
        // and the part visibly unlike the STEP. This runs before subtraction so
        // the query sees the clean box edges, not the mouth-opening perimeter.
        if (WG_ENCLOSURE.edge > 0 * millimeter)
        {{
            var enclosureEdges = qCreatedBy(id + "wgEnclosure", EntityType.EDGE);
            if (WG_ENCLOSURE.edgeType == 2)
            {{
                opChamfer(context, id + "wgEdge", {{
                        "entities" : enclosureEdges,
                        "chamferType" : ChamferType.EQUAL_OFFSETS,
                        "width" : WG_ENCLOSURE.edge
                }});
            }}
            else
            {{
                opFillet(context, id + "wgEdge", {{
                        "entities" : enclosureEdges,
                        "radius" : WG_ENCLOSURE.edge
                }});
            }}
        }}

        // ---- the bore becomes a cavity, after the box is finished ----
        opBoolean(context, id + "wgSubtract", {{
                "tools" : qCreatedBy(id + "wgLoft", EntityType.BODY),
                "targets" : qCreatedBy(id + "wgEnclosure", EntityType.BODY),
                "operationType" : BooleanOperationType.SUBTRACTION
        }});

        setProperty(context, {{
                "entities" : qCreatedBy(id + "wgEnclosure", EntityType.BODY),
                "propertyType" : PropertyType.NAME,
                "value" : "WG waveguide"
        }});
    }});
'''


__all__ = ["FEATURE_TYPE", "STD_VERSION", "build_featurescript", "ring_stations"]
