#!/bin/sh
# Waveguide Generator, installed. Do not edit: this file is generated by
# scripts/build_bundle.py and replaced wholesale by every update.
set -eu

self=$0
# `readlink -f` is coreutils and BSD-incompatible, which is fine: this file
# only ever runs on the Linux bundle it was built into.
if command -v readlink >/dev/null 2>&1; then
    resolved=$(readlink -f "$self" 2>/dev/null || printf '%s' "$self")
else
    resolved=$self
fi
here=$(CDPATH= cd -- "$(dirname -- "$resolved")" && pwd -P)

app=$here/app
python=$here/runtime/bin/python3.13
recovery=$here/recovery/wg_bundle_recovery.py

# An interrupted update leaves the app layer, the runtime layer, or both
# renamed aside. Neither is where the recovery that fixes it used to live, so
# it lives in `recovery` beside them, and the interpreter that runs it is
# whichever of the two runtime copies survived. Absolute paths inside the
# installation only: nothing here is taken from PATH or from the data
# directory.
if [ ! -d "$app" ] || [ ! -x "$python" ]; then
    if [ ! -x "$python" ] && [ -x "$here/runtime.previous/bin/python3.13" ]; then
        python=$here/runtime.previous/bin/python3.13
    fi
    if [ -x "$python" ] && [ -f "$recovery" ]; then
        "$python" "$recovery" --resources "$here" -- "$@" || true
    fi
fi

if [ ! -d "$app" ] || [ ! -x "$here/runtime/bin/python3.13" ]; then
    printf 'Waveguide Generator launcher: the installation at %s is incomplete.\n' "$here" >&2
    printf 'Reinstall it by running install.sh from the release tarball.\n' >&2
    exit 71
fi
python=$here/runtime/bin/python3.13

WG2_BUNDLE=1
WG2_APP_ROOT=$app
export WG2_BUNDLE WG2_APP_ROOT

cache=${XDG_CACHE_HOME:-$HOME/.cache}/waveguide-generator
PYTHONPYCACHEPREFIX=$cache/pycache
NUMBA_CACHE_DIR=$cache/numba
export PYTHONPYCACHEPREFIX NUMBA_CACHE_DIR

cd -- "$app" || exit 71
exec "$python" -m launchers.desktop "$@"
