"""The scope gate counts bodies, and a surface body is one body.

Reported against a Fusion-first half model (PartyMEH): the add-in's manifest
declares one exterior body, WG refused the import with "STEP contains 26
exterior bodies; manifest declares 1", and the file was correct.

Both sides of that contract are written down. The producer counts one body per
``MANIFOLD_SOLID_BREP`` or ``SHELL_BASED_SURFACE_MODEL``
(``wglink_send.count_step_bodies``, and ``wglink_send`` refuses its own export
when its inventory disagrees, so the manifest is known to be counting bodies).
Fusion writes a surface body as ``SHELL_BASED_SURFACE_MODEL('name',
(#open_shell))`` -- the layout ``hornlab_mesher.step_import._parse_named_shell_faces``
is written against -- and OCC imports that one shell as one free surface *per
face*. The consumer was counting those surfaces.

The fixtures below are **synthetic**, generated by :mod:`_shell_fixture`. They
are not captured Fusion exports and are not claimed to be: what they reproduce
is the STEP topology the standard allows and Fusion uses. Each one is imported
through OCC and meshed, so a fixture that is merely parseable text cannot pass.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from server.mesh.gmsh_worker import _run_in_gmsh_session
from server.mesh.imported import _import_occ_root_bodies, occ_body_groups

from _shell_fixture import write_disjoint_shells, write_open_shell


def _inventory(step_path: Path) -> dict[str, object]:
    """Import, group, and prove the geometry is real by meshing it."""

    import gmsh

    def probe() -> dict[str, object]:
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.clear()
        roots = _import_occ_root_bodies(gmsh, step_path)
        groups = occ_body_groups(gmsh, roots)
        gmsh.option.setNumber("Mesh.MeshSizeMax", 0.5)
        gmsh.model.mesh.generate(2)
        _types, tags, _nodes = gmsh.model.mesh.getElements(2)
        elements = sum(len(group) for group in tags)
        gmsh.clear()
        return {"roots": len(roots), "bodies": len(groups),
                "group_sizes": sorted(len(group) for group in groups),
                "mesh_elements": elements}

    return _run_in_gmsh_session(probe)


def test_one_open_shell_of_several_faces_is_one_body(tmp_path: Path) -> None:
    """The reported case, in the smallest topology that has it.

    Two planar faces sharing one ``EDGE_CURVE``, in a single ``OPEN_SHELL``
    inside a single ``SHELL_BASED_SURFACE_MODEL``. CAD calls that one body; so
    must this. The root count stays at one per face, because that is what an
    affine transform has to touch exactly once -- the two answers are different
    questions about the same import, and conflating them is what refused the
    user's model.
    """

    step = write_open_shell(tmp_path / "one-shell.step", faces=2)
    inventory = _inventory(step)

    assert inventory["bodies"] == 1, inventory
    assert inventory["roots"] == 2, "each face is still transformed exactly once"
    assert inventory["group_sizes"] == [2]
    assert inventory["mesh_elements"] > 0, "the fixture must be meshable geometry"


def test_an_undeclared_second_shell_is_still_a_second_body(tmp_path: Path) -> None:
    """The property the fix must not trade away.

    Grouping free faces is not "every free face is one body". Two shells that
    share no edge are two bodies, so a STEP carrying an undeclared extra shell
    still fails the scope gate against a manifest that declares one.
    """

    step = write_disjoint_shells(tmp_path / "two-shells.step")
    inventory = _inventory(step)

    assert inventory["bodies"] == 2, inventory
    assert inventory["group_sizes"] == [2, 2]


def test_a_solid_and_a_free_shell_are_two_bodies(tmp_path: Path) -> None:
    """A volume is a body on its own, whatever its faces are doing.

    The standalone source sheet the importer preserves is a real interface, so
    a solid plus a sheet must read as two -- not as one plus however many faces
    the sheet has.
    """

    import gmsh

    step = write_open_shell(tmp_path / "sheet.step", faces=2)

    def probe() -> dict[str, object]:
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.clear()
        gmsh.model.occ.importShapes(str(step), highestDimOnly=False)
        gmsh.model.occ.addBox(5.0, 5.0, 5.0, 1.0, 1.0, 1.0)
        gmsh.model.occ.synchronize()
        roots = [(3, int(tag)) for _dim, tag in gmsh.model.getEntities(3)]
        roots.extend(
            (2, int(tag))
            for _dim, tag in gmsh.model.getEntities(2)
            if len(gmsh.model.getAdjacencies(2, int(tag))[0]) == 0
        )
        groups = occ_body_groups(gmsh, roots)
        gmsh.clear()
        return {"roots": len(roots), "bodies": len(groups),
                "sizes": sorted(len(group) for group in groups)}

    inventory = probe() if gmsh.isInitialized() else _run_in_gmsh_session(probe)
    assert inventory["bodies"] == 2, inventory
    assert inventory["sizes"] == [1, 2], "one volume, one two-face shell"


@pytest.mark.parametrize("faces", [2, 3, 4])
def test_a_shell_is_one_body_however_many_faces_it_has(tmp_path: Path, faces: int) -> None:
    """The count must not depend on how finely the surface body is divided."""

    step = write_open_shell(tmp_path / f"shell-{faces}.step", faces=faces)
    inventory = _inventory(step)

    assert inventory["bodies"] == 1, inventory
    assert inventory["roots"] == faces
